name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.1.1
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  wakelock_plus: ^1.1.1
  meta: ^1.8.0
  flutter_widget_from_html_core: ^0.10.3
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.0
  collection: ^1.17.1
  xml: ^6.3.0

dev_dependencies:
  lint: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin